# Service configuration
service:
  host: 127.0.0.1
  port: 3000
  baseUrl: /api/v1/lirest

# Database configuration
postgres:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: '123456'
  database: 'lirest'
  schema: 'users'

# API documentation configuration
api-docs:
  username: ''
  password: ''

# Log configuration
log:
  level: info
